In [77]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.externals import joblib 

c:\users\mudracircle\appdata\local\programs\python\python36\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [25]:
df = pd.read_csv('dataset.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
age         303 non-null int64
sex         303 non-null int64
cp          303 non-null int64
trestbps    303 non-null int64
chol        303 non-null int64
fbs         303 non-null int64
restecg     303 non-null int64
thalach     303 non-null int64
exang       303 non-null int64
oldpeak     303 non-null float64
slope       303 non-null int64
ca          303 non-null int64
thal        303 non-null int64
target      303 non-null int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [27]:
df.describe()

age         sex          cp    trestbps        chol         fbs  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean    54.366337    0.683168    0.966997  131.623762  246.264026    0.148515   
std      9.082101    0.466011    1.032052   17.538143   51.830751    0.356198   
min     29.000000    0.000000    0.000000   94.000000  126.000000    0.000000   
25%     47.500000    0.000000    0.000000  120.000000  211.000000    0.000000   
50%     55.000000    1.000000    1.000000  130.000000  240.000000    0.000000   
75%     61.000000    1.000000    2.000000  140.000000  274.500000    0.000000   
max     77.000000    1.000000    3.000000  200.000000  564.000000    1.000000   

          restecg     thalach       exang     oldpeak       slope          ca  \
count  303.000000  303.000000  303.000000  303.000000  303.000000  303.000000   
mean     0.528053  149.646865    0.326733    1.039604    1.399340    0.729373   
std      0.525860   22.905161    0.469794    1.161075    0.616226    1.022606   
min      0.000000   71.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000  133.500000    0.000000    0.000000    1.000000    0.000000   
50%      1.000000  153.000000    0.000000    0.800000    1.000000    0.000000   
75%      1.000000  166.000000    1.000000    1.600000    2.000000    1.000000   
max      2.000000  202.000000    1.000000    6.200000    2.000000    4.000000   

             thal      target  
count  303.000000  303.000000  
mean     2.313531    0.544554  
std      0.612277    0.498835  
min      0.000000    0.000000  
25%      2.000000    0.000000  
50%      2.000000    1.000000  
75%      3.000000    1.000000  
max      3.000000    1.000000

In [28]:
df['target'].value_counts()

1    165
0    138
Name: target, dtype: int64

In [29]:
df.dtypes

age           int64
sex           int64
cp            int64
trestbps      int64
chol          int64
fbs           int64
restecg       int64
thalach       int64
exang         int64
oldpeak     float64
slope         int64
ca            int64
thal          int64
target        int64
dtype: object

In [31]:
print(df['chol'].max())
print(df['trestbps'].max())
print(df['thalach'].max())

564
200
202


In [32]:
#chol_max = df['chol'].max()
chol_max = 564
df['chol'] = df['chol']/chol_max
df['chol'].head()

0    0.413121
1    0.443262
2    0.361702
3    0.418440
4    0.627660
Name: chol, dtype: float64

In [33]:
#trestbps_max = df['trestbps'].max()
trestbps_max = 200
df['trestbps']=df['trestbps']/trestbps_max
df['trestbps'].head()

0    0.725
1    0.650
2    0.650
3    0.600
4    0.600
Name: trestbps, dtype: float64

In [34]:
#thalach_max = df['thalach'].max()
thalach_max = 202
df['thalach']=df['thalach']/thalach_max
df['thalach'].head()

0    0.742574
1    0.925743
2    0.851485
3    0.881188
4    0.806931
Name: thalach, dtype: float64

In [35]:
X = df.iloc[:, :-1].values
X

array([[63.,  1.,  3., ...,  0.,  0.,  1.],
       [37.,  1.,  2., ...,  0.,  0.,  2.],
       [41.,  0.,  1., ...,  2.,  0.,  2.],
       ...,
       [68.,  1.,  0., ...,  1.,  2.,  3.],
       [57.,  1.,  0., ...,  1.,  1.,  3.],
       [57.,  0.,  1., ...,  1.,  1.,  2.]])

In [36]:
y = df.iloc[:,13]
y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

In [37]:
#Splitting the dataset into Train and Test
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=0)

In [38]:
# scaling the dataset
sc_X=StandardScaler()
X_train=sc_X.fit_transform(X_train)
X_test=sc_X.transform(X_test)

In [39]:
# Using KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors = 6)

In [40]:
#Shape of train and test data
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (242, 13) (242,)
Test set: (61, 13) (61,)


In [41]:
knn_classifier.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=6, p=2,
                     weights='uniform')

In [42]:
prediction = knn_classifier.predict(X_test)

In [43]:
prediction1 = pd.DataFrame(prediction)
prediction1.head()

0
0  0
1  0
2  0
3  0
4  0

In [44]:
#Accuracy
from sklearn import metrics
metrics.accuracy_score(y_test, prediction)

0.8360655737704918

In [45]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [86]:
list1 = [67,1,0,160,286,0,0,108,1,1.5,1,3,2]
df2 = pd.DataFrame([list1],columns=['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
                                       'exang', 'oldpeak', 'slope', 'ca', 'thal'])
df2.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   67    1   0       160   286    0        0      108      1      1.5      1   

   ca  thal  
0   3     2

In [87]:
df2['chol'] = df2['chol']/chol_max
df2['trestbps']=df2['trestbps']/trestbps_max
df2['thalach']=df2['thalach']/thalach_max

In [88]:
df2.head()

age  sex  cp  trestbps      chol  fbs  restecg   thalach  exang  oldpeak  \
0   67    1   0       0.8  0.507092    0        0  0.534653      1      1.5   

   slope  ca  thal  
0      1   3     2

In [89]:
result_X = df2.iloc[:, :].values

In [90]:
result_X

array([[67.        ,  1.        ,  0.        ,  0.8       ,  0.5070922 ,
         0.        ,  0.        ,  0.53465347,  1.        ,  1.5       ,
         1.        ,  3.        ,  2.        ]])

In [74]:
pre = knn_classifier.predict(result_X)

In [75]:
pre

array([0], dtype=int64)

In [78]:
joblib.dump(knn_classifier, 'knn_01.pkl')

['knn_01.pkl']

In [79]:
knn_from_joblib = joblib.load('knn_01.pkl')

In [91]:
knn_from_joblib.predict(result_X) 

array([0], dtype=int64)